site_name: Tutorial Linux (Espa√±ol)

nav:
  - Index : index.md
  - Que es Linux : queeslinux.md
  - Instalacion : instalacion.md
  - Estructura Linux : estructura.md
  - Archivos : archivos.md
  - Usuarios : usuarios.md

theme:
  name: material
  # Opcional: colores personalizados
  palette:
    primary: teal
    accent: amber
